/*
Steven Nguyen
101603439
*/
/* 
SUBJECT(SUBJCODE, DESCRIPTION)
PRIMARY KEY (SUBJCODE)
TEACHER(STAFFID, SURNAME, GIVENAME)
PRIMARY KEY (STAFFID)
STUDENT(STUDENTID, SURNAME, GIVENNAME, GENDER)
PRIMARY KEY (STUDENTID)
SUBJECTOFFERING(SUBJCODE, YEAR, SEMESTER, FEE, STAFFID)
PRIMARY KEY (SUBJCODE, YEAR, SEMESTER)
FOREIGN KEY (STAFFID) REFERENCES TEACHER
FOREGIN KEY (SUBJCODE) REFERENCES SUBJECT
ENROLMENT (STUDENTID, SUBJCODE, YEAR, SEMESTER, DATEENROLLED, GRADE)
PRIMARY KEY (STUDENTID, SUBJCODE, YEAR, SEMESTER)
FOFOREIGN KEY (STUDENID) REFERENCES STUDENT
FOREIGN KEY (SUBJCODE, YEAR, SEMESTER) REFERENCING SUBJECTOFFERING
*/

DROP TABLE IF EXISTS ENROLMENT3439,SUBJECTOFFERING3439, STUDENT3439, TEACHER3439, SUBJECT3439;
GO
CREATE TABLE SUBJECT3439(
      SUBJCODE        NVARCHAR(100)
    , DESCRIPTION    NVARCHAR(100)
    , PRIMARY KEY (SUBJCODE)
)

CREATE TABLE TEACHER3439(
      STAFFID   INT
    , SURNAME   NVARCHAR(100)   NOT NULL
    , GIVENAME  NVARCHAR(100)   NOT NULL
    , PRIMARY KEY (STAFFID)
    , CONSTRAINT CHK_TEACHER_STAFFID CHECK(LEN(STAFFID)=8 )
)

CREATE TABLE STUDENT3439(
      STUDENTID NVARCHAR(10)
    , SURNAME   NVARCHAR(100)   NOT NULL
    , GIVENNAME NVARCHAR(100)   NOT NULL
    , GENDER    NVARCHAR(1)
    , PRIMARY KEY (STUDENTID)
    , CONSTRAINT CHK_STUDENT_GENDER CHECK(GENDER IN ('M', 'F', 'i'))
)

CREATE TABLE SUBJECTOFFERING3439(
      SUBJCODE NVARCHAR(100)
    , YEAR  INT
    , SEMESTER  INT
    , FEE   MONEY   NOT NULL
    , STAFFID   INT
    , PRIMARY KEY (SUBJCODE, YEAR, SEMESTER)
    , FOREIGN KEY (SUBJCODE) REFERENCES SUBJECT3439
    , FOREIGN KEY (STAFFID) REFERENCES TEACHER3439
    , CONSTRAINT CHK_SUBJOFF_YEAR CHECK(LEN(YEAR)=8 )
    , CONSTRAINT CHK_SUBJOFF_SEMESTER CHECK(SEMESTER IN (1,2))
    , CONSTRAINT CHK_SUBJOFF_FEE CHECK(FEE > 0)
)

CREATE TABLE ENROLMENT3439(
      STUDENTID NVARCHAR(10)
    , SUBJCODE  NVARCHAR(100)
    , YEAR  INT
    , SEMESTER  INT
    , DATEENROLLED  DATE
    , GRADE NVARCHAR(2) DEFAULT NULL
    , PRIMARY KEY (STUDENTID, SUBJCODE, YEAR, SEMESTER)
    , FOREIGN KEY (STUDENTID) REFERENCES STUDENT3439
    , FOREIGN KEY (SUBJCODE, YEAR, SEMESTER) REFERENCES SUBJECTOFFERING3439
    , CONSTRAINT CHK_ENROLMENT_YEAR CHECK(LEN(YEAR)=8 )
    , CONSTRAINT CHK_ENROLMENT_SEMESTER CHECK(SEMESTER IN (1,2))
    , CONSTRAINT CHK_ENROLMENT_GRADE CHECK(GRADE IN('N', 'P', 'C', 'D', 'HD'))
)

SELECT NAME 
FROM SYS.objects
WHERE TYPE = 'U'
