/*
Steven Nguyen
101603439
*/
/* 

SUBJECT(SUBJCODE, DESCRIPTION)
PRIMARY KEY (SUBJCODE)
TEACHER(STAFFID, SURNAME, GIVENAME)
PRIMARY KEY (STAFFID)
STUDENT(STUDENTID, SURNAME, GIVENNAME, GENDER)
PRIMARY KEY (STUDENTID)
SUBJECTOFFERING(SUBJCODE, YEAR, SEMESTER, FEE, STAFFID)
PRIMARY KEY (SUBJCODE, YEAR, SEMESTER)
FOREIGN KEY (STAFFID) REFERENCES TEACHER
FOREGIN KEY (SUBJCODE) REFERENCES (SUBJECT)
ENROLMENT (STUDENTID, SUBJCODE, YEAR, SEMESTER, DATEENROLLED, GRADE)
PRIMARY KEY (STUDENTID, SUBJCODE, YEAR, SEMESTER)
FOFOREIGN KEY (STUDENID) REFERENCES STUDENT
FOREIGN KY (SUBJCODE, YEAR, SEMESTER) REFERENCING SUBJECTOFFERING
*/